[pytest]
# Где искать тесты
testpaths = tests

# Какие файлы считать тестами
python_files = test_*.py *_test.py

# Какие функции считать тестами
python_functions = test_*

# Какие классы считать тестами
python_classes = Test*

# Показывать print() в тестах
addopts = -v --tb=short